version: 1
disable_existing_loggers: False

formatters:
  simple:
    style: "{"
    format: "SIMPLE FORMATTER: {asctime} - {name} -{levelname} - {message}"

  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)% %(name)% %(levelname)% %(message)% %(funcName)%"

handlers:
  console:
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout

  file:
    formatter: json
    class: logging.handlers.RotatingFileHandler
    filename: logs/app.logs.jsonl
    level: DEBUG
    maxBytes: 10000
    backupCount: 3

root:
  level: WARNING
  handlers: [console]

loggers:
  app:
    level: DEBUG
    handlers: [file]
    propagate: no
